version: '3.6'

services:
  project-jupyterlab:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: jupterylab-server
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - './:/opt/jupyterlab'